State: 7
Info: ''
Logo: pack://application:,,,/Plain Craft Launcher 2;component/Images/Blocks/NeoForge.png
ReleaseTime: 2024-08-08 20:24
VersionFabric: ''
VersionLegacyFabric: ''
VersionQuilt: ''
VersionLabyMod: ''
VersionOptiFine: ''
VersionLiteLoader: false
VersionForge: ''
VersionNeoForge: 21.1.236
VersionCleanroom: ''
VersionVanillaName: 1.21.1
VersionVanilla: 21.0.1
LogoCustom: false
VersionArgumentIndieV2: true
VersionLaunchCount: 3
