VersionLiteLoader:False
Info:正式版 1.21.1, NeoForge 21.1.236
VersionVanilla:21.0.1
VersionRamType:0
VersionArgumentTitle:Chemical&Create : New Horizon | 0.1.1a
VersionRamOptimize:1
VersionVanillaName:1.21.1
VersionNeoForge:21.1.236
ReleaseTime:2024-08-08 20:24
Logo:pack://application:,,,/Plain Craft Launcher 2;component/Images/Blocks/NeoForge.png
VersionArgumentIndieV2:True
VersionArgumentInfo:
State:7
