blank_issues_enabled: false
contact_links:
  - name: '漏洞反馈'
    url: https://github.com/TeaCafeStudio/ChemicalAndCreate-NewHorizon-TestVersion/issues/new?template=bug.yml
    about: '报告与整合包相关的 bug'
  - name: '优化建议'
    url: https://github.com/TeaCafeStudio/ChemicalAndCreate-NewHorizon-TestVersion/issues/new?template=optimize.yml
    about: '提出对整合包的优化建议与新功能建设'
  - name: '新功能投票'
    url: https://github.com/TeaCafeStudio/ChemicalAndCreate-NewHorizon-TestVersion/discussions/categories/%E6%96%B0%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8
    about: '一些新玩法、新功能需要在社区投票之后才能上线'
  - name: '赞助我们一杯热咖啡！☕️'
    url: https://ifdian.net/a/teacafe
    about: '创作不易，你的支持就是我们的最大动力！让我们用爱发电！'
